In [2]:
import cv2
import os
import time
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
model = tf.keras.models.load_model("mlp.model") 

In [3]:
def point_trans_contrast_dynamic(image, m, e):
    image = image.astype(np.float32) / 255
    trans_image = 1/(1+(m/image)**e)
    norm_image = cv2.normalize(trans_image, None, alpha = 0, beta = 255, norm_type = cv2.NORM_MINMAX, dtype = cv2.CV_32F)
    trans_image = norm_image.astype(np.uint8)
    return trans_image

def point_trans_gamma(image, const, gamma):
    image = image.astype(np.float32) / 255
    trans_image = (image**gamma)*const
    norm_image = cv2.normalize(trans_image, None, alpha = 0, beta = 255, norm_type = cv2.NORM_MINMAX, dtype = cv2.CV_32F)
    trans_image = norm_image.astype(np.uint8)
    return trans_image

def crop(image ,x_a, x_b, y_a, y_b):
    image_croped = image[x_a:x_b, y_a:y_b] 
    return image_croped

def convert(frame): #transformations used for lerning model
    frame = cv2.resize(frame, (256, 180))                
    frame = crop(frame, 0, 180, 38, 218) 
    return frame
    
def prepare(frame):
    return frame.reshape((-1, 97200))

In [ ]:
cap = cv2.VideoCapture(1) 

while cap.isOpened(): 
    ret, frame = cap.read()
    frame = convert(frame)
    
    prediction = model.predict(prepare(frame)) 
    print(prediction)
    if prediction[0][0] < prediction[0][1]:
        cv2.imshow('correct', frame)
        print('correct')
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    else:
        cv2.imshow('bad', frame)
        print('bad')
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break;
        
cap.release()
cv2.destroyAllWindows()

[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[1. 0.]]
bad
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[1. 0.]]
bad
[[1. 0.]]
bad
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[1. 0.]]
bad
[[1. 0.]]
bad
[[0. 1.]]
correct
[[0. 1.]]
correct
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[0. 1.]]
correct
[[0. 1.]]
correct
[[1. 0.]]
bad
[[1. 0.]]
bad
[[0. 1.]]
correct
[[1.000000e+00 6.870275e-15]]
bad
[[2.191052e-15 1.000000e+00]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[1.0000000e+00 1.6545875e-22]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[1. 0.]]
bad
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]

[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct
[[0. 1.]]
correct


In [ ]:
#PRZETRENOWANY BO DAJE CORRECT DZIWNYM RZECZOM CZASEM

In [ ]:
#W PRZYSZLOSCI WEZWIE ZEW PROGRAM PO API,  
#CAP.OPEN() WZIECIE KLIKU RAMEK JAK WSZYSTKIE ZGODNE TO WYNIK I CAP.RELEASE()
#JAK NIEZGODNE TO NIEPEWNY WYNIK
#JAK BRAK DOSTEPU DO KAMERKI ITP TO BLAD